// apiConstants.js

const ACTIVE_REQUEST_STALE_MINUTES = 15;

const ACTIVE_LIMIT = 25;
const MAX_TRACKED_REQUESTS = 30;
const STALE_REQUEST_AGE_MS =
  ACTIVE_REQUEST_STALE_MINUTES *
  RuntimeConstants.SECONDS_PER_MINUTE *
  RuntimeConstants.MS_PER_SECOND;
const USER_REQUEST_STORE_KEY = 'AB_USER_REQUEST_STORE';

const LOCK_TIMEOUT_MS = 1000;
const LOCK_WAIT_WARN_THRESHOLD_MS = 300;

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    ACTIVE_LIMIT,
    MAX_TRACKED_REQUESTS,
    STALE_REQUEST_AGE_MS,
    USER_REQUEST_STORE_KEY,
    LOCK_TIMEOUT_MS,
    LOCK_WAIT_WARN_THRESHOLD_MS,
  };
}
