apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: langflow-backend
  namespace: default
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    autoscaling.knative.dev/maxScale: '1' # Concurrent instances with shared in-memory volumes don't work terribly well atm. If you want to improve speed, up the number of workers and core count instead. 
    run.googleapis.com/execution-environment: gen2
    run.googleapis.com/sessionAffinity: 'true'

spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/sessionAffinity: 'true'
        run.googleapis.com/cpu-throttling: 'false'
      labels:
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 160
      timeoutSeconds: 240
      serviceAccountName: <SERVICE_ACCOUNT_NAME> # Create a service account with sufficient permissions to run a Cloud Run instance.
      containers:
      - name: langflow-backend
      # Note: This docker image is a slightly modified version of the official Langflow one that runs as root to ensure compatability with Google Cloud Run's in-memory volumes.
      # You can see the dockerfile here: https://github.com/h-arnold/langflow/blob/main/docker/build_and_push_root.Dockerfile
        image: eu.gcr.io/assessment-bot-8axvxh/langflow-backend:latest 
        ports:
        - name: http1
          containerPort: 7860
        env:
        - name: LANGFLOW_PORT
          value: '7860'
        - name: LANGFLOW_AUTO_LOGIN
          value: 'FALSE'
        - name: LANGFLOW_SUPERUSER
          value: <SUPERUSER> 
        - name: LANGFLOW_WORKERS
          value: '1' # If you're using the supabase free Postgres instance, any more than one worker causes issues with direct connections and you can't use the connection pooler because that means that prepare parameters can't be used, which are used by langflow.
        - name: LANGFLOW_SAVE_DB_IN_CONFIG_DIR
          value: 'FALSE'
        - name: LANGFLOW_STORE_ENVIRONMENT_VARIABLES
          value: 'TRUE'
        - name: LANGFLOW_BACKEND_ONLY
          value: 'TRUE'
        - name: LANGFLOW_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: <SUPERUSER_PASSWORD_SECRET>
              key: latest
        - name: LANGFLOW_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: <DATABASE_URL_SECRET>
              key: latest
        resources:
          limits:
            cpu: 2000m # As a general rule of thumb, each Langflow worker needs 1CPU and 1GB or RAM.
            memory: 2Gi
        volumeMounts:
        - name: cockroachRootCert
          mountPath: /app/data/.postgres
        - name: data
          mountPath: /root/.cache/langflow/
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 7860
      volumes:
      - name: cockroachRootCert
        secret:
          secretName: <POSTGRES_CERT_SECRET>
          items:
          - key: '1'
            path: root.crt
      - name: data
        emptyDir:
          medium: Memory
          sizeLimit: 512Mi - # A 10 slide activity with a class of 32 students will take around 48Mb so this is enough for 4 of those.
  traffic:
  - percent: 100
