steps:
  # Step 1: Checkout the code from the default branch
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'git'
    args: ['clone', 'https://github.com/h-arnold/googleSLidesAssessor.git']

  # Step 2: Build a Docker image using the specified Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-f', 'src/backend/langflow/docker/ramdisk.Dockerfile',
      '-t', 'eu.gcr.io/$PROJECT_ID/langflow-backend:latest',
      'src/backend/langflow/docker'  # Sets the context to the Dockerfile's directory
    ]

  # Step 3: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/langflow-backend:latest']

images:
  - 'eu.gcr.io/$PROJECT_ID/langflow-backend:latest'

timeout: '1200s'  # Build timeout set to 20 minutes (adjust as needed)

options:
  logging: CLOUD_LOGGING_ONLY
