name: Push to Google Apps Script

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Push to Google Apps Script
        uses: daikikatsuragawa/clasp-action@v1
        with:
          # Google service account credentials (JSON format)
          # Create this secret in your repository settings
          credentials: ${{ secrets.CLASP_CREDENTIALS }}
          
          # Google Apps Script project ID
          # Create this secret in your repository settings
          script_id: ${{ secrets.HEAD_APP_SCRIPT_ID}}
          
          # Command to execute (push is default)
          command: 'push'
