name: Push to Google Apps Script

on:
  push:
    branches:
      - "*" # Trigger on push to any branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push code to Google Apps Script        
        uses: Mayu-mic/google-apps-script-action@v2
        with:
          clasprc: ${{ secrets.CLASPRC_JSON }}
          scriptId: ${{ secrets.HEAD_APP_SCRIPT_ID }}
          sourceRootDir: 'src/fontend'
          command: 'push'
